version: '2.2'
services:
  cert_tools_api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    working_dir: /app/cert_tools
    command: bash -c "pip install -r requirements.txt && /start-reload.sh"
    container_name: cert_tools_api
    mem_limit: 512000000
    memswap_limit: 512000000
    mem_swappiness: 0
    user: "0:0"
    environment:
      - app=development
    volumes:
      - ./app/cert_tools_api.py:/app/main.py
      - ../cert-tools:/app/cert_tools
      #- ../cert-issuer/data/pdf_certificates:/app/cert_tools/sample_data/pdf_certificates
    #restart: unless-stopped
    ports:
      - 7000:80


  cert_issuer_api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    volumes:
      - ./app/cert_issuer_api.py:/app/main.py
      - ../cert-issuer:/app/cert_issuer
      - ../cert-tools/sample_data/unsigned_certificates:/app/cert_issuer/data/unsigned_certificates
    working_dir: /app/cert_issuer
    command: bash -c "pip3 install -r ethereum_smart_contract_requirements.txt && /start-reload.sh"
    container_name: cert_issuer_api
    mem_limit: 512000000
    memswap_limit: 512000000
    mem_swappiness: 0
    user: "0:0"
    environment:
      - app=development
    #restart: unless-stopped
    ports:
      - 7001:80

# TODO: Wait for improved IPNS performance before integrating in production.
  ipfs:
    image: ipfs/go-ipfs:v0.6.0
    environment:
    #  - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ../ipfsdata:/ipfsdata
    ports:
      - "4001:4001"
      - "8080:8080"
      - "8081:8081"
      - "5001:5001"

